---
- name: Add the OS specific variables
  include_vars: '{{ ansible_os_family }}.yml'
  tags:
    - ntp

- name: Install Prerequisite Packages
  yum:
    name={{ package.name }}
    state={{ package.state }}
  when: ansible_os_family == 'RedHat'
  tags:
    - ntp

- name: Install Prerequisite Packages
  apt:
    name={{ package.name }}
    state={{ package.state }}
  when: ansible_os_family == 'Debian'
  tags:
    - ntp

- name: Copy ntp.conf
  template:
    src=ntp.conf.j2
    dest=/etc/ntp.conf
  notify:
    - Restart NTP
  tags:
    - ntp
